# Generated by Django 6.0.1 on 2026-02-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.PositiveIntegerField()),
                ('duration_months', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'course',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
