# Generated by Django 6.0.1 on 2026-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
            ],
        ),
    ]
