# Generated by Django 6.0.1 on 2026-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_coordinates', models.CharField(max_length=255)),
                ('total_capacity', models.PositiveIntegerField()),
                ('layout_description', models.TextField(blank=True)),
            ],
        ),
    ]
