# Generated by Django 6.0.1 on 2026-02-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_parkinglot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id_code', models.CharField(max_length=50, unique=True)),
                ('slot_type', models.CharField(choices=[('regular', 'Regular'), ('ev', 'Electric Vehicle'), ('handicap', 'Handicap-accessible')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Test.parkinglot')),
            ],
        ),
    ]
