# Generated by Django 6.0.1 on 2026-02-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_count', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.parkinglot')),
            ],
        ),
    ]
