# Generated by Django 6.0.1 on 2026-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_product_productdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDuration', models.CharField(max_length=50)),
                ('courseFee', models.IntegerField()),
                ('courseMode', models.CharField(choices=[('online', 'Online'), ('ofline', 'Ofline')], max_length=20)),
                ('courseActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
