# Generated by Django 6.0.1 on 2026-02-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentHobbies', models.CharField(choices=[('reading', 'reading'), ('travelling', 'travelling'), ('dancing', 'dancing')], max_length=400)),
                ('studentAddress', models.CharField(max_length=100)),
                ('studentPhone', models.CharField(max_length=10)),
                ('studentGeender', models.CharField(max_length=10)),
                ('studentDOB', models.DateField()),
                ('studentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'StudentProfile',
            },
        ),
    ]
