# Generated by Django 6.0.1 on 2026-02-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_category_customer_customerprofile_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'book_category',
            },
        ),
        migrations.AlterModelTable(
            name='customerprofile',
            table='customer profile',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('bookPrice', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.bookcategory')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
